include:
  - project: pipelines/pipelines
    ref: master
    file:
      - "/jobs/build.yaml"
      - "/jobs/docker.yaml"
      - "/jobs/rules.yaml"

.global-variables:
  variables:
    SSH_USER: "$ENV_SSH_USER"
    SSH_HOST: "$ENV_SSH_HOST"
    SSH_PRIVATE_KEY_BASE64: "$ENV_PRIVATE_KEY_BASE64"

stages:
  - build
  - deploy

build:
  stage: build
  extends:
    - .build
    - .rules-merge-or-master

deploy:
  stage: deploy
  extends:
    - .docker_run
    - .global-variables
    - .rules-merge-or-master
  script:
    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - apk update && apk add docker-compose
    - echo "Запуск Docker Compose с prod профилем..."
    - docker-compose -f docker-compose.yaml --profile prod up --build -d
    - docker-compose ps
  variables:
    OPT_DOCKER: "-p 80:80"

  # only:
  #   refs:
  #     - main

# default:
#   before_script:
#     - docker info
#     - docker-compose version

services:
  - docker:dind

